apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "voxrelay.fullname" . }}-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.primary.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "voxrelay.fullname" . }}-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.master.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "voxrelay.fullname" . }}-minio-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
