apiVersion: v1
kind: Secret
metadata:
  name: voxrelay-secrets
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | quote }}
  jwt-access-secret: {{ .Values.secrets.jwtAccessSecret | quote }}
  jwt-refresh-secret: {{ .Values.secrets.jwtRefreshSecret | quote }}
  cookie-secret: {{ .Values.secrets.cookieSecret | quote }}
  minio-access-key: {{ .Values.secrets.minioAccessKey | quote }}
  minio-secret-key: {{ .Values.secrets.minioSecretKey | quote }}
  turn-secret: {{ .Values.secrets.turnSecret | quote }}
