apiVersion: v1
kind: Service
metadata:
  name: {{ include "voxrelay.fullname" . }}-auth
  labels:
    app.kubernetes.io/component: auth-service
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voxrelay.fullname" . }}-channel
  labels:
    app.kubernetes.io/component: channel-svc
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: channel-svc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voxrelay.fullname" . }}-media
  labels:
    app.kubernetes.io/component: media-sfu
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: media-sfu
