apiVersion: v2
name: voxrelay
description: VoxRelay PTT — Push-to-Talk communication platform
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - ptt
  - push-to-talk
  - mediasoup
  - webrtc
sources:
  - https://github.com/redlline/VoxrelayPTT
